### ISSUE TITLE
:-) Will this project continue to be maintained?

### ISSUE THREAD

**Issue by a943915349** [lecousin/lc-spring-data-r2dbc#3]
:-) Will this project continue to be maintained?

**Comment by lecousin** [comment]
Hi,
Yes as long as people find it useful, it can be maintained.
I will upgrade dependencies to the latest versions.
If you have an issue, you can open a proper issue. If you miss a feature, you can propose it in the discussions (or even better do a pull request ;).
Please prefer to open a discussion than an issue if this is not a bug.
