### ISSUE TITLE
Circular dependency on latest Spring version (2.6.x)

### ISSUE THREAD

**Issue by iamceph** [lecousin/lc-spring-data-r2dbc#5]
Heyo, I got an Circular dependency exception while starting Spring.
I am using latest Spring and Postgres, running this configuration with application.yaml.

Here is the error: `https://paste.gg/p/anonymous/77b4004078a04a7cad6a346ed0b7951a`

How can I solve this? Thank you.

**Comment by lecousin** [comment]
Hi,
I can reproduce when I upgrade to the latest Spring version (2.6.x), but not with previous versions.
I will provide a new version soon compatible with the latest Spring version.

**Comment by lecousin** [comment]
The version 0.5.0 has been released and is compatible with Spring version 2.6.1
Can you upgrade your dependency version and tell me if it solves your issue ?

**Comment by iamceph** [comment]
Solved the issue, thank you.

**Comment by iamceph** [comment]
I also want to ask, is there a way to not use the yaml file for entities?

**Comment by iamceph** [comment]
Giving the choice sounds good to me, thank you :)

**Comment by lecousin** [comment]
The version 0.5.1 is available and the yaml file is now optional
