### ISSUE TITLE
Failed to Enhance classes

### ISSUE THREAD

**Issue by iamceph** [lecousin/lc-spring-data-r2dbc#6]
It seems that I am unable to Enhance the classes. Can you please look into it?

Error: https://paste.gg/p/anonymous/7e2154a42b4d4c94824c5c84fb5133b7

**Comment by lecousin** [comment]
Which Java version are you using ?

**Comment by iamceph** [comment]
I am using Java 17. I tried with the latest version without the .yaml file, but I still get similar error.
It seems that the cause is here: https://github.com/lecousin/lc-spring-data-r2dbc/blob/master/core/src/main/java/net/lecousin/reactive/data/relational/enhance/Enhancer.java#L108

Here is the entity class: https://paste.gg/p/anonymous/30296f0898ce45909d768b5d3aa027a6
Here is the base class: https://paste.gg/p/anonymous/1fea8a4147354b4685f907ac3bd93571

Thank you for your time.

**Comment by iamceph** [comment]
I tried that, sadly it does not help at all.

**Comment by lecousin** [comment]
My analysis is that newest Java versions do not allow anymore to modify a class in another package for security reasons. The possible way to do it (as javassist does) is to know a "neighbor" class (another class in the same package).

To make it easy, I can propose that in the entities packages you need to put a class, which is not an entity, named "AllowEnhancer" (it can be just an interface). I agree that this workaround is not perfect, and not really pretty, but at least it works. Does it sounds acceptable for you as a workaround for now ? And I will try to find a prettier solution then.

**Comment by iamceph** [comment]
Sounds alright to me for now, thanks

**Comment by iamceph** [comment]
Seems like the latest version did not got to Maven Central :(

**Comment by lecousin** [comment]
Yes I was waiting for Maven Central before to post, but it was very slow on their side to validate and publish the new version. It is now available.

**Comment by iamceph** [comment]
Tested with this workaround, works for now :)
